# Generated by Django 3.2.16 on 2023-06-25 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_class',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
