# Generated by Django 3.2.16 on 2023-06-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20230613_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='permissions_name',
            field=models.CharField(max_length=15, unique=True, verbose_name='权限名称'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(max_length=15, unique=True, verbose_name='角色名称'),
        ),
    ]
