# Generated by Django 3.2.16 on 2023-06-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_auto_20230613_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='permissions_status',
            field=models.BooleanField(default=True, verbose_name='权限状态'),
        ),
    ]
