# Generated by Django 3.2.16 on 2023-06-25 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0006_alter_permissions_permissions_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='role_status',
        ),
    ]
