# Generated by Django 3.2.16 on 2023-06-25 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0007_remove_role_role_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='角色名称'),
        ),
    ]
