# Generated by Django 3.2.16 on 2023-06-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0008_alter_role_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permissions',
            name='permissions_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='权限名称'),
        ),
    ]
